source 'http://rubygems.org'

gem 'rails', '3.2.13'
gem 'jquery-rails'

group :production do 
 gem "pg"
end

group :development, :test do
  gem "sqlite3-ruby", "~> 1.3.0", :require => "sqlite3"
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# AdWords API gem.
gem 'google-adwords-api', '~> 0.9.0'
# Gem for OAuth authorization.
gem 'oauth2'
