source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use postgresql as the database for Active Record
gem "mysql2", "~> 0.3.13"

# File upload orm mapping
gem "carrierwave", "~> 0.9.0"
gem "fog", "~> 1.15.0"

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Flexible authentication solution for Rails
gem 'omniauth'
gem "omniauth-google-oauth2", "~> 0.2.1"
gem 'protected_attributes'

# Twitter's Bootstrap, converted to Sass and ready to drop into Rails or Compass
gem 'bootstrap-sass', '~> 2.3.2.2'

# High performance memcached client for Ruby
gem "dalli", "~> 2.6.4"

# Web server for production performance
gem 'thin', '~> 1.5.1'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# unique ID generation library.
gem 'uuidtools', '2.1.4'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '1.3.0'

# Paginated queries
gem 'kaminari', '0.14.1'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# ActiveRecord backend for Delayed::Job
gem 'delayed_job_active_record', '4.0.0'

# Web interface for delayed_job inspired by resque
gem 'delayed_job_web', '1.2.0'

# Call JavaScript code and manipulate JavaScript objects from Ruby. Call Ruby code and manipulate Ruby objects from JavaScript.
gem 'therubyracer', '0.12.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# jQuery UI's JavaScript, CSS, and image files packaged for the Rails 3.1+ asset pipeline
gem 'jquery-ui-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :test do
	gem 'rspec-rails'
	gem 'cucumber-rails'
	gem 'capybara'
	gem 'database_cleaner'
end

group :development do
	gem 'faker'
	gem 'populator'
	gem 'erb2haml'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]