# ruby encoding: utf-8
ImagenLocal.delete_all
Local.delete_all
Comentario.delete_all
Keyword.delete_all
NegocioCerrado.delete_all
Producto.delete_all
Distribuidor.delete_all
Productor.delete_all
User.delete_all

###Productores
productor1 = Productor.create(nombre: "Carolina Suarez", nit_cedula: "12323422", logo_o_foto: "fotoproductor1.png", descripcion: "Diseñadora de modas, especialista en bolsos", motivacion_registro: "Diversificar mi mercado", calificacion: "5")
productor1.keyword.create(tag: "bolsos")
productor1.keyword.create(tag: "carteras")
producto1 = productor1.producto.create(nombre: "Cama", url_imagen: "producto1.png", descripcion: "Cama doble ultramoderna")
productor2 = Productor.create(nombre: "Cariñitos S.A.S", nit_cedula: "34343422-0", logo_o_foto: "fotoproductor2.png", descripcion: "Los mejores osos del mercado.", motivacion_registro: "Quiero llegar a nuevos clientes", calificacion: "3")
productor2.keyword.create(tag: "osos")
productor2.keyword.create(tag: "peluches")
producto2 = productor2.producto.create(nombre: "Osito soñador", url_imagen: "producto1.png", descripcion: "Osito soñador de la diseñadora Claudia Zuleta")
productor3 = Productor.create(nombre: "Cocinitas LTDA", nit_cedula: "98798734", logo_o_foto: "fotoproductor3.png", descripcion: "Todo para la cocina y algo mas.", motivacion_registro: "Conseguir mejores precios por mi producto", calificacion: "4")
productor3.keyword.create(tag: "cocina")
productor3.keyword.create(tag: "culinaria")
producto3 = productor3.producto.create(nombre: "Ollas en acero inoxidable", url_imagen: "producto1.png", descripcion: "Set de ollas con aleación")
productor4 = Productor.create(nombre: "Diseños a su gusto", nit_cedula: "7654323", logo_o_foto: "fotoproductor4.png", descripcion: "Los mejores diseños al mejor precio.", motivacion_registro: "Quiero probar el sistema", calificacion: "0")
productor4.keyword.create(tag: "lampara")
productor4.keyword.create(tag: "new design")
producto4 = productor4.producto.create(nombre: "Lampara de pie", url_imagen: "producto1.png", descripcion: "Del diseñador Oscar Bustamente moderna lampara con iluminación calida.")
productor5 = Productor.create(nombre: "Importadores asociados", nit_cedula: "987654", logo_o_foto: "fotoproductor5.png", descripcion: "Importamos lo mejor para el hogar", motivacion_registro: "Me hablaron mucho de este sistema", calificacion: "4")
productor5.keyword.create(tag: "vajillas")
productor5.keyword.create(tag: "ceramica")
producto5 = productor5.producto.create(nombre: "Platos Corelle", url_imagen: "producto1.png", descripcion: "Durable vajilla con adornos en plata y decoración de aves.")
productor6 = Productor.create(nombre: "Aceros Modelia", nit_cedula: "34534356", logo_o_foto: "fotoproductor6.png", descripcion: "Los mejores productos en acero inoxidable.", motivacion_registro: "Quiero hacer nuevos negocios", calificacion: "3")
productor6.keyword.create(tag: "cocina")
productor6.keyword.create(tag: "metales")
producto6 = productor6.producto.create(nombre: "Cafetera OXY", url_imagen: "producto1.png", descripcion: "Caliente super rápido y prepare el mejor café, también prepara capuccino.")
productor7 = Productor.create(nombre: "Bisuteria a su gusto", nit_cedula: "3453453", logo_o_foto: "fotoproductor7.png", descripcion: "Fabricamos aretes y anillos en madera muy autoctonos.", motivacion_registro: "Confio encontrar quien venda lo que hacemos.", calificacion: "1")
productor7.keyword.create(tag: "madera")
productor7.keyword.create(tag: "bisuteria")
producto7 = productor7.producto.create(nombre: "Set de aretes en madera", url_imagen: "producto1.png", descripcion: "Diseñados y fabricados en exclusiva por nuestro distribuidor Alberto Echeverry")
productor8 = Productor.create(nombre: "Jorge Bermudez S.A.S", nit_cedula: "123123443", logo_o_foto: "fotoproductor8.png", descripcion: "Diseñador industrial apasionado por el arte.", motivacion_registro: "Llegar a otros países", calificacion: "5")
productor8.keyword.create(tag: "Joyeria")
productor8.keyword.create(tag: "artes metalicas")
producto8 = productor8.producto.create(nombre: "Anillo en plata nivel 5", url_imagen: "producto1.png", descripcion: "La casa de joyeros buendia nos regala una joya de calidad para las amantes de la belleza y el glamour.")

###Distribuidores
distribuidor1 = Distribuidor.create(nombre: "Ventas y servicios al detal", nit_cedula: "23423123", nombre_representante_legal: "Carolina Duarte", logo_o_foto: "company1.png", descripcion: "Compañia dedicada a la venta de productos inmobiliarios", motivacion_registro: "Me parece interesante su sistema", calificacion: "4")
distribuidor1.keyword.create(tag: "madera")
distribuidor1.keyword.create(tag: "detal")
distribuidor1.keyword.create(tag: "peluches")
distribuidor1.keyword.create(tag: "utensilios cocina")
distribuidor1.comentario.create(comentario: "Gente muy confiable, les entregué mis productos y los vendieron todos super rápido, pagaron a tiempo")
distribuidor1.comentario.create(comentario: "Los locales estan muy bien ubicados cerca a zonas comerciales muy transitadas.")
distribuidor1.comentario.create(comentario: "Tuve dificultades por la distancia!. Todos los locales estan en el norte y yo vivo en el sur.")
distribuidor1.comentario.create(comentario: "Me pagaron la mercancia muy rápido. La mayoria de distribuidores que venden mis productos tardan mas de 3 meses en pagar.")
local1 = distribuidor1.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5845224", lon: "-74.0861589", comentario: "Excelente ubicación en la zona mas prestigiosa de la ciudad.")
local1.imagen_local.create(url: "distribuidor1_local1_1.png")
local1.imagen_local.create(url: "distribuidor1_local1_2.png")
local1.imagen_local.create(url: "distribuidor1_local1_3.png")
local1.imagen_local.create(url: "distribuidor1_local1_4.png")
local2 = distribuidor1.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5844261", lon: "-74.0830797", comentario: "Excelente ubicación en la zona mas prestigiosa de la ciudad.")
local2.imagen_local.create(url: "distribuidor1_local1_1.png")
local2.imagen_local.create(url: "distribuidor1_local1_2.png")
local2.imagen_local.create(url: "distribuidor1_local1_3.png")
local2.imagen_local.create(url: "distribuidor1_local1_4.png")
local3 = distribuidor1.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5805547", lon: "-74.0823179", comentario: "A una cuadra del mayor centro comercial de la ciudad, y con un amplio espacio, tres plantas y 6800 metros cuadrados y estanterias. Lo mejor en el mejor lugar.")
local3.imagen_local.create(url: "distribuidor1_local1_1.png")
local3.imagen_local.create(url: "distribuidor1_local1_2.png")
local3.imagen_local.create(url: "distribuidor1_local1_3.png")
local3.imagen_local.create(url: "distribuidor1_local1_4.png")
local4 = distribuidor1.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5711007", lon: "-74.0802044", comentario: "La boutique mas exclusiva que puede encontrar, solo vendemos lo mejor y de los mejores!.")
local4.imagen_local.create(url: "distribuidor1_local1_1.png")
local4.imagen_local.create(url: "distribuidor1_local1_2.png")
local4.imagen_local.create(url: "distribuidor1_local1_3.png")
local4.imagen_local.create(url: "distribuidor1_local1_4.png")
distribuidor1.negocio_cerrado.create(acuerdo: "Pago en efectivo contra entrega", condiciones: "Mercancia entregada cada 15 días durante 1 mes", calificacion_transaccion_distribuidor: "5", calificacion_transaccion_productor: "5", producto_id: producto5.id)

###Distribuidores
distribuidor2 = Distribuidor.create(nombre: "Grandes superficies de occidente", nit_cedula: "879876799", nombre_representante_legal: "Hernan Andrade", logo_o_foto: "company1.png", descripcion: "Compañia dedicada a la venta de productos inmobiliarios", motivacion_registro: "Busco nuevos e innovadores productos", calificacion: "4")
distribuidor2.keyword.create(tag: "electrodomesticos")
distribuidor2.keyword.create(tag: "cocina")
distribuidor2.keyword.create(tag: "hogar")
distribuidor2.keyword.create(tag: "limpieza")
distribuidor2.comentario.create(comentario: "Gente muy confiable, les entregué mis productos y los vendieron todos super rápido, pagaron a tiempo")
distribuidor2.comentario.create(comentario: "Los locales estan muy bien ubicados cerca a zonas comerciales muy transitadas.")
distribuidor2.comentario.create(comentario: "Tuve dificultades por la distancia!. Todos los locales estan en el norte y yo vivo en el sur.")
distribuidor2.comentario.create(comentario: "Me pagaron la mercancia muy rápido. La mayoria de distribuidores que venden mis productos tardan mas de 3 meses en pagar.")
local1 = distribuidor2.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5845230", lon: "-74.0861592", comentario: "Excelente ubicación en la zona mas prestigiosa de la ciudad.")
local1.imagen_local.create(url: "distribuidor1_local1_1.png")
local1.imagen_local.create(url: "distribuidor1_local1_2.png")
local1.imagen_local.create(url: "distribuidor1_local1_3.png")
local1.imagen_local.create(url: "distribuidor1_local1_4.png")
local2 = distribuidor2.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5844212", lon: "-74.0830782", comentario: "Excelente ubicación en la zona mas prestigiosa de la ciudad.")
local2.imagen_local.create(url: "distribuidor1_local1_1.png")
local2.imagen_local.create(url: "distribuidor1_local1_2.png")
local2.imagen_local.create(url: "distribuidor1_local1_3.png")
local2.imagen_local.create(url: "distribuidor1_local1_4.png")
local3 = distribuidor2.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5805598", lon: "-74.0823130", comentario: "A una cuadra del mayor centro comercial de la ciudad, y con un amplio espacio, tres plantas y 6800 metros cuadrados y estanterias. Lo mejor en el mejor lugar.")
local3.imagen_local.create(url: "distribuidor1_local1_1.png")
local3.imagen_local.create(url: "distribuidor1_local1_2.png")
local3.imagen_local.create(url: "distribuidor1_local1_3.png")
local3.imagen_local.create(url: "distribuidor1_local1_4.png")
local4 = distribuidor2.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5711018", lon: "-74.0802021", comentario: "La boutique mas exclusiva que puede encontrar, solo vendemos lo mejor y de los mejores!.")
local4.imagen_local.create(url: "distribuidor1_local1_1.png")
local4.imagen_local.create(url: "distribuidor1_local1_2.png")
local4.imagen_local.create(url: "distribuidor1_local1_3.png")
local4.imagen_local.create(url: "distribuidor1_local1_4.png")
distribuidor2.negocio_cerrado.create(acuerdo: "Pago en efectivo contra entrega", condiciones: "Mercancia entregada cada 15 días durante 1 mes", calificacion_transaccion_distribuidor: "5", calificacion_transaccion_productor: "5", producto_id: producto5.id)

###Distribuidores
distribuidor3 = Distribuidor.create(nombre: "Pinilla y Asociados", nit_cedula: "879876799", nombre_representante_legal: "Hernan Andrade", logo_o_foto: "company1.png", descripcion: "Compañia dedicada a la venta de productos inmobiliarios", motivacion_registro: "Busco nuevos e innovadores productos", calificacion: "4")
distribuidor3.keyword.create(tag: "computadores")
distribuidor3.keyword.create(tag: "libros")
distribuidor3.keyword.create(tag: "herramientas industriales")
distribuidor3.keyword.create(tag: "arte")
distribuidor3.comentario.create(comentario: "Gente muy confiable, les entregué mis productos y los vendieron todos super rápido, pagaron a tiempo")
distribuidor3.comentario.create(comentario: "Los locales estan muy bien ubicados cerca a zonas comerciales muy transitadas.")
distribuidor3.comentario.create(comentario: "Tuve dificultades por la distancia!. Todos los locales estan en el norte y yo vivo en el sur.")
distribuidor3.comentario.create(comentario: "Me pagaron la mercancia muy rápido. La mayoria de distribuidores que venden mis productos tardan mas de 3 meses en pagar.")
local1 = distribuidor3.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5845230", lon: "-74.0861592", comentario: "Excelente ubicación en la zona mas prestigiosa de la ciudad.")
local1.imagen_local.create(url: "distribuidor1_local1_1.png")
local1.imagen_local.create(url: "distribuidor1_local1_2.png")
local1.imagen_local.create(url: "distribuidor1_local1_3.png")
local1.imagen_local.create(url: "distribuidor1_local1_4.png")
local2 = distribuidor3.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5812219", lon: "-74.0820790", comentario: "Excelente ubicación en la zona mas prestigiosa de la ciudad.")
local2.imagen_local.create(url: "distribuidor1_local1_1.png")
local2.imagen_local.create(url: "distribuidor1_local1_2.png")
local2.imagen_local.create(url: "distribuidor1_local1_3.png")
local2.imagen_local.create(url: "distribuidor1_local1_4.png")
local3 = distribuidor3.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5887532", lon: "-74.0825123", comentario: "A una cuadra del mayor centro comercial de la ciudad, y con un amplio espacio, tres plantas y 6800 metros cuadrados y estanterias. Lo mejor en el mejor lugar.")
local3.imagen_local.create(url: "distribuidor1_local1_1.png")
local3.imagen_local.create(url: "distribuidor1_local1_2.png")
local3.imagen_local.create(url: "distribuidor1_local1_3.png")
local3.imagen_local.create(url: "distribuidor1_local1_4.png")
local4 = distribuidor3.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5711054", lon: "-74.0802021", comentario: "La boutique mas exclusiva que puede encontrar, solo vendemos lo mejor y de los mejores!.")
local4.imagen_local.create(url: "distribuidor1_local1_1.png")
local4.imagen_local.create(url: "distribuidor1_local1_2.png")
local4.imagen_local.create(url: "distribuidor1_local1_3.png")
local4.imagen_local.create(url: "distribuidor1_local1_4.png")
distribuidor3.negocio_cerrado.create(acuerdo: "Pago en efectivo contra entrega", condiciones: "Mercancia entregada cada 15 días durante 1 mes", calificacion_transaccion_distribuidor: "5", calificacion_transaccion_productor: "5", producto_id: producto5.id)

###Distribuidores
distribuidor4 = Distribuidor.create(nombre: "Tiendas Carolina", nit_cedula: "32423453", nombre_representante_legal: "Carolina Diaz", logo_o_foto: "company1.png", descripcion: "Servicios y productos de panaderia", motivacion_registro: "Busco mejores proveedores", calificacion: "4")
distribuidor4.keyword.create(tag: "panaderia")
distribuidor4.keyword.create(tag: "pasteles")
distribuidor4.keyword.create(tag: "postres")
distribuidor4.comentario.create(comentario: "Gente muy confiable, les entregué mis productos y los vendieron todos super rápido, pagaron a tiempo")
distribuidor4.comentario.create(comentario: "Los locales estan muy bien ubicados cerca a zonas comerciales muy transitadas.")
distribuidor4.comentario.create(comentario: "Tuve dificultades por la distancia!. Todos los locales estan en el norte y yo vivo en el sur.")
distribuidor4.comentario.create(comentario: "Me pagaron la mercancia muy rápido. La mayoria de distribuidores que venden mis productos tardan mas de 3 meses en pagar.")
local1 = distribuidor4.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5835230", lon: "-74.0861592", comentario: "Excelente ubicación en la zona mas prestigiosa de la ciudad.")
local1.imagen_local.create(url: "distribuidor1_local1_1.png")
local1.imagen_local.create(url: "distribuidor1_local1_2.png")
local1.imagen_local.create(url: "distribuidor1_local1_3.png")
local1.imagen_local.create(url: "distribuidor1_local1_4.png")
local2 = distribuidor4.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5819619", lon: "-74.0822780", comentario: "Excelente ubicación en la zona mas prestigiosa de la ciudad.")
local2.imagen_local.create(url: "distribuidor1_local1_1.png")
local2.imagen_local.create(url: "distribuidor1_local1_2.png")
local2.imagen_local.create(url: "distribuidor1_local1_3.png")
local2.imagen_local.create(url: "distribuidor1_local1_4.png")
local3 = distribuidor4.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5877932", lon: "-74.0828133", comentario: "A una cuadra del mayor centro comercial de la ciudad, y con un amplio espacio, tres plantas y 6800 metros cuadrados y estanterias. Lo mejor en el mejor lugar.")
local3.imagen_local.create(url: "distribuidor1_local1_1.png")
local3.imagen_local.create(url: "distribuidor1_local1_2.png")
local3.imagen_local.create(url: "distribuidor1_local1_3.png")
local3.imagen_local.create(url: "distribuidor1_local1_4.png")
local4 = distribuidor4.local.create(ciudad: "Bogota", pais: "Colombia", lat: "4.5721084", lon: "-74.0812731", comentario: "La boutique mas exclusiva que puede encontrar, solo vendemos lo mejor y de los mejores!.")
local4.imagen_local.create(url: "distribuidor1_local1_1.png")
local4.imagen_local.create(url: "distribuidor1_local1_2.png")
local4.imagen_local.create(url: "distribuidor1_local1_3.png")
local4.imagen_local.create(url: "distribuidor1_local1_4.png")
distribuidor3.negocio_cerrado.create(acuerdo: "Pago en efectivo contra entrega", condiciones: "Mercancia entregada cada 15 días durante 1 mes", calificacion_transaccion_distribuidor: "5", calificacion_transaccion_productor: "5", producto_id: producto5.id)