application: dezkareid
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /
  script: index.py
  secure: always

- url: /.*
  script: error.py