# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise32"

  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network :forwarded_port, guest: 8000, host: 8001

  config.vm.synced_folder "../website", "/home/vagrant/django_site", :mount_options => ["dmode=755,fmode=755"]

  config.vm.provision "shell", path: "boot.sh"
end
