application: hotstreetapp
version: 1
runtime: python27
api_version: 1
threadsafe: true
#default_expiration: "5d"

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /humans.txt
  static_files: st/humans.txt
  upload: st/humans.txt
  http_headers:
    Content-type: 'text/plain; charset=utf-8'

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /getinfo
  script: oget.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: ssl
  version: latest
