application: agile-business
version: 2
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /_ah/spi/.*
  script: run.api

- url: /media
  static_dir: app/media

- url: /.*
  script: run.app