application: vaifreteapp2
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: django
  version: "1.4"

builtins:
- django_wsgi: on

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /admin/.*
  script: main.py
  login: admin

- url: /app/.*
  script: main.py
  login: required

- url: /DeliveryService.*
  script: services.py

- url: .*
  script: main.py